import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Wrapper from './Wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Change Detection',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-gradient-to-b from-blue-900 to-purple-900 h-screen`}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
